[package]
name = "bootupd"
version = "0.1.0"
authors = ["Colin Walters <walters@verbum.org>"]
edition = "2018"

[lib]
name = "bootupd"
path = "src/bootupd.rs"

[[bin]]
name = "bootupd"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
serde = "1.0.112"
serde_derive = "1.0.112"
serde_json = "1.0"
serde_yaml = "0.8"
typetag = "0.1"
libc = "0.2"
fs2 = "0.4.3"
nix = "0.17.0"
tempfile = "3.0.3"
clap = "~2.33"
structopt = "0.3"
openat = "0.1.19"
openat-ext = "0.1.0"
openssl = "^0.10"
libsystemd = "^0.2"
hex = "0.4.2"
bincode = "1.3.1"
bs58 = "0.3.1"
byteorder = "1"
rayon = "1.0"
c_utf8 = "0.1.0"
lazy_static = "1.1.0"
serde_plain = "0.3.0"
chrono = { version = "0.4.11", features = ["serde"] }

[profile.release]
# Saves some text and I think is a better practice anyways
panic = "abort"
# We assume we're being delivered via e.g. RPM which supports split debuginfo
debug = true
